name: CICD Static Deployment

on:
  push:
    branches:
      - main
jobs:
  deploy:   
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOSTS }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEYS }}
          script: |
            cd /home/ubuntu/heroku-static-site
            sudo git pull origin main
            echo "Done"